nodeLinker: node-modules
nmHoistingLimits: workspaces
yarnPath: .yarn/releases/yarn-3.3.1.cjs
enableInlineBuilds: true
nmMode: hardlinks-local

packageExtensions:
  "@types/postcss-nested@*":
    peerDependencies:
      postcss: "*"